project_id = "purpuvwtrgrisxstactq"

[functions.couples-game]
verify_jwt = false

[functions.elevenlabs-sfx]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-music]
verify_jwt = false

[functions.og-invite]
verify_jwt = false